bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: ssC3dPt1aqiDkEEfXSdWTdfiMiW149g0ghGv8LENnbwYRR0r66MdR2wgNpdMTDVn+6RbxFfxOi+7EtrtHbAbFX+DLZcOnUXpQfGmnWcdAWEz8rMwY3QrJPqONdpg190Td3jNY2ihauAGFoaYy+QpTZunRfqEKxFM2hT5wkucCVBHtZEc3962ic1Vgra22yO3LJJ6ymzCq5bdvRy1OL42jb2dQFnaJdIGV+o0y7Ju8SHSshRkqpcfD1vgu9+TMCVQ7ttBiJmgVURMCKvoytBzHsm5VKMme7W2dyPCoAm86pTT7dkxYjIdThqQm+Sbwsm29W8vQ22k3i7PCW3SdDtizBZwahd6/s3+sgmHPVOyOH8xAZGdNaCMr9P+EvtDI4PUTDc3GCvdfcWHlRHzFYDE5JY5HDkgfLAnSGR2HI6A59B7vpgND2jlx8nY3Ta0+yL4mAOFad78HwphOlYzDiI5gZRFbI6QbegXSL3QSTiT4qOMwxtxk1dsZK5KVulIZErEQVHExQN1nqvduS211ceTVvTA7sVx+/pheQVRZuvoh8vZxX9Oune2uDBInOAkaTlCJo6ymiHL5qkTl2xPcfmP0DEP9nD5YkumzYV7FajhKLo7Ld21NB6AJd5SjghE5PFA+FDAsZlcfbKai1jtIhaA2wnuNh3fbIg38QQOQHVVMSc=
conda_forge_output_validation: true
